  on:
    release:
      types: [created]
  jobs:
    deploy:
      if: github.event_name == 'release' && contains(github.event.release.tag_name, 'v')
      runs-on: ubuntu-latest
      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64, linux/arm/v8
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/passwdgen:$ {{ github.event.release.tag_name }}