name: Python application PR

on:
    pull_request:
        branches:
        - main

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Run tests
          run: pytest
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Docker build
          run: docker build -t passwdGen .
        - name: Docker run
          run: docker run -d -p 5000:5000 --name passwdGen passwdGen
        - name: Deploy
          run: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag myapp $DOCKERHUB_USERNAME/passwdGen:latest
            docker push $DOCKERHUB_USERNAME/passwdGen:latest
